# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/xuxu/work/data-structure

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/xuxu/work/data-structure

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xuxu/work/data-structure/CMakeFiles /home/xuxu/work/data-structure/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xuxu/work/data-structure/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named xxlib

# Build rule for target.
xxlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xxlib
.PHONY : xxlib

# fast build rule for target.
xxlib/fast:
	$(MAKE) -f CMakeFiles/xxlib.dir/build.make CMakeFiles/xxlib.dir/build
.PHONY : xxlib/fast

#=============================================================================
# Target rules for targets named StaticArray-test

# Build rule for target.
StaticArray-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 StaticArray-test
.PHONY : StaticArray-test

# fast build rule for target.
StaticArray-test/fast:
	$(MAKE) -f test/CMakeFiles/StaticArray-test.dir/build.make test/CMakeFiles/StaticArray-test.dir/build
.PHONY : StaticArray-test/fast

#=============================================================================
# Target rules for targets named LinkList-test

# Build rule for target.
LinkList-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LinkList-test
.PHONY : LinkList-test

# fast build rule for target.
LinkList-test/fast:
	$(MAKE) -f test/CMakeFiles/LinkList-test.dir/build.make test/CMakeFiles/LinkList-test.dir/build
.PHONY : LinkList-test/fast

#=============================================================================
# Target rules for targets named CircleList-test

# Build rule for target.
CircleList-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CircleList-test
.PHONY : CircleList-test

# fast build rule for target.
CircleList-test/fast:
	$(MAKE) -f test/CMakeFiles/CircleList-test.dir/build.make test/CMakeFiles/CircleList-test.dir/build
.PHONY : CircleList-test/fast

#=============================================================================
# Target rules for targets named StaticLinkList-test

# Build rule for target.
StaticLinkList-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 StaticLinkList-test
.PHONY : StaticLinkList-test

# fast build rule for target.
StaticLinkList-test/fast:
	$(MAKE) -f test/CMakeFiles/StaticLinkList-test.dir/build.make test/CMakeFiles/StaticLinkList-test.dir/build
.PHONY : StaticLinkList-test/fast

#=============================================================================
# Target rules for targets named DualLinkList-test

# Build rule for target.
DualLinkList-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DualLinkList-test
.PHONY : DualLinkList-test

# fast build rule for target.
DualLinkList-test/fast:
	$(MAKE) -f test/CMakeFiles/DualLinkList-test.dir/build.make test/CMakeFiles/DualLinkList-test.dir/build
.PHONY : DualLinkList-test/fast

#=============================================================================
# Target rules for targets named DynamicList-test

# Build rule for target.
DynamicList-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DynamicList-test
.PHONY : DynamicList-test

# fast build rule for target.
DynamicList-test/fast:
	$(MAKE) -f test/CMakeFiles/DynamicList-test.dir/build.make test/CMakeFiles/DynamicList-test.dir/build
.PHONY : DynamicList-test/fast

#=============================================================================
# Target rules for targets named StaticList-test

# Build rule for target.
StaticList-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 StaticList-test
.PHONY : StaticList-test

# fast build rule for target.
StaticList-test/fast:
	$(MAKE) -f test/CMakeFiles/StaticList-test.dir/build.make test/CMakeFiles/StaticList-test.dir/build
.PHONY : StaticList-test/fast

#=============================================================================
# Target rules for targets named testmian

# Build rule for target.
testmian: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testmian
.PHONY : testmian

# fast build rule for target.
testmian/fast:
	$(MAKE) -f test/CMakeFiles/testmian.dir/build.make test/CMakeFiles/testmian.dir/build
.PHONY : testmian/fast

#=============================================================================
# Target rules for targets named DynamicArray-test

# Build rule for target.
DynamicArray-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DynamicArray-test
.PHONY : DynamicArray-test

# fast build rule for target.
DynamicArray-test/fast:
	$(MAKE) -f test/CMakeFiles/DynamicArray-test.dir/build.make test/CMakeFiles/DynamicArray-test.dir/build
.PHONY : DynamicArray-test/fast

#=============================================================================
# Target rules for targets named SmartPointer-test

# Build rule for target.
SmartPointer-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SmartPointer-test
.PHONY : SmartPointer-test

# fast build rule for target.
SmartPointer-test/fast:
	$(MAKE) -f test/CMakeFiles/SmartPointer-test.dir/build.make test/CMakeFiles/SmartPointer-test.dir/build
.PHONY : SmartPointer-test/fast

Common/Object.o: Common/Object.cpp.o

.PHONY : Common/Object.o

# target to build an object file
Common/Object.cpp.o:
	$(MAKE) -f CMakeFiles/xxlib.dir/build.make CMakeFiles/xxlib.dir/Common/Object.cpp.o
.PHONY : Common/Object.cpp.o

Common/Object.i: Common/Object.cpp.i

.PHONY : Common/Object.i

# target to preprocess a source file
Common/Object.cpp.i:
	$(MAKE) -f CMakeFiles/xxlib.dir/build.make CMakeFiles/xxlib.dir/Common/Object.cpp.i
.PHONY : Common/Object.cpp.i

Common/Object.s: Common/Object.cpp.s

.PHONY : Common/Object.s

# target to generate assembly for a file
Common/Object.cpp.s:
	$(MAKE) -f CMakeFiles/xxlib.dir/build.make CMakeFiles/xxlib.dir/Common/Object.cpp.s
.PHONY : Common/Object.cpp.s

Exception/Exception.o: Exception/Exception.cpp.o

.PHONY : Exception/Exception.o

# target to build an object file
Exception/Exception.cpp.o:
	$(MAKE) -f CMakeFiles/xxlib.dir/build.make CMakeFiles/xxlib.dir/Exception/Exception.cpp.o
.PHONY : Exception/Exception.cpp.o

Exception/Exception.i: Exception/Exception.cpp.i

.PHONY : Exception/Exception.i

# target to preprocess a source file
Exception/Exception.cpp.i:
	$(MAKE) -f CMakeFiles/xxlib.dir/build.make CMakeFiles/xxlib.dir/Exception/Exception.cpp.i
.PHONY : Exception/Exception.cpp.i

Exception/Exception.s: Exception/Exception.cpp.s

.PHONY : Exception/Exception.s

# target to generate assembly for a file
Exception/Exception.cpp.s:
	$(MAKE) -f CMakeFiles/xxlib.dir/build.make CMakeFiles/xxlib.dir/Exception/Exception.cpp.s
.PHONY : Exception/Exception.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... xxlib"
	@echo "... StaticArray-test"
	@echo "... LinkList-test"
	@echo "... CircleList-test"
	@echo "... StaticLinkList-test"
	@echo "... DualLinkList-test"
	@echo "... DynamicList-test"
	@echo "... StaticList-test"
	@echo "... testmian"
	@echo "... DynamicArray-test"
	@echo "... SmartPointer-test"
	@echo "... Common/Object.o"
	@echo "... Common/Object.i"
	@echo "... Common/Object.s"
	@echo "... Exception/Exception.o"
	@echo "... Exception/Exception.i"
	@echo "... Exception/Exception.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

